[project]
name = "slurm-glance"
version = "0.1.0"
description = "A simple web dashboard for Slurm HPC status."
requires-python = ">=3.8"
dependencies = [
    "flask",
    "fabric",
]

[project.scripts]
slurpy = "dashboard_server:main"

[tool.setuptools]
# Explicitly tell setuptools that the only Python module is dashboard_server.py
py-modules = ["dashboard_server"]
# Allow inclusion of data files
include-package-data = true

# Explicitly tell setuptools which data files to include, specifically the content 
# of the templates and static folders, even though they are at the top level.
[tool.setuptools.package-data]
"*" = ["templates/*", "static/*", "static/**/*"]